### ISSUE TITLE
gym.error.UnregisteredEnv: No registered env with id: EnergyPlus-v0

### ISSUE THREAD

**Issue by flag2freefish** [IBM/rl-testbed-for-energyplus#63]
after running `time python3 -m baselines_energyplus.trpo_mpi.run_energyplus --num-timesteps 1000000000` with EnergyPlus-9-3-0 in  Ubuntu18.04 on Windows 10

WARNING:tensorflow:From /home/yhl/EP/rl-testbed-for-energyplus/src/baselines/baselines/common/tf_util.py:63: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /home/yhl/EP/rl-testbed-for-energyplus/src/baselines/baselines/common/tf_util.py:72: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2021-09-01 16:32:43.294147: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-09-01 16:32:43.297234: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2304005000 Hz
2021-09-01 16:32:43.297420: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4426b30 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-09-01 16:32:43.297448: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
train: init logger with dir=/home/yhl/eplog/openai-2021-09-01-16-32-43-298104
Logging to /home/yhl/eplog/openai-2021-09-01-16-32-43-298104
Traceback (most recent call last):
  File "/home/yhl/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 132, in spec
    return self.env_specs[id]
KeyError: 'EnergyPlus-v0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yhl/EP/rl-testbed-for-energyplus/baselines_energyplus/trpo_mpi/run_energyplus.py", line 56, in <module>
    main()
  File "/home/yhl/EP/rl-testbed-for-energyplus/baselines_energyplus/trpo_mpi/run_energyplus.py", line 53, in main
    train(args.env, num_timesteps=args.num_timesteps, seed=args.seed)
  File "/home/yhl/EP/rl-testbed-for-energyplus/baselines_energyplus/trpo_mpi/run_energyplus.py", line 41, in train
    env = make_energyplus_env(env_id, workerseed)
  File "/home/yhl/EP/rl-testbed-for-energyplus/baselines_energyplus/common/energyplus_util.py", line 19, in make_energyplus_env
    env = gym.make(env_id)
  File "/home/yhl/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "/home/yhl/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 100, in make
    spec = self.spec(path)
  File "/home/yhl/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 142, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: EnergyPlus-v0

real    0m1.702s
user    0m1.747s
sys     0m1.399s

**Comment by flag2freefish** [comment]
first

# Specify the top directory
TOP=<DOWNLOAD-DIRECTORY>/rl-testbed-for-energyplus
export PYTHONPATH=${PYTHONPATH}:${TOP}

if [ `uname` == "Darwin" ]; then
	energyplus_instdir="/Applications"
else
	energyplus_instdir="/usr/local"
fi
ENERGYPLUS_VERSION="8-8-0"
#ENERGYPLUS_VERSION="9-1-0"
#ENERGYPLUS_VERSION="9-2-0"
#ENERGYPLUS_VERSION="9-3-0"
**### ENERGYPLUS_DIR**="${energyplus_instdir}/EnergyPlus-${ENERGYPLUS_VERSION}"
modified ENERGYPLUS="${energyplus_instdir}/EnergyPlus-${ENERGYPLUS_VERSION}"
WEATHER_DIR="${ENERGYPLUS_DIR}/WeatherData"
export ENERGYPLUS="${ENERGYPLUS_DIR}/energyplus"
MODEL_DIR="${TOP}/EnergyPlus/Model-${ENERGYPLUS_VERSION}"

# Weather file.
# Single weather file or multiple weather files separated by comma character.
export ENERGYPLUS_WEATHER="${WEATHER_DIR}/USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw"
#export ENERGYPLUS_WEATHER="${WEATHER_DIR}/USA_CO_Golden-NREL.724666_TMY3.epw"
#export ENERGYPLUS_WEATHER="${WEATHER_DIR}/USA_FL_Tampa.Intl.AP.722110_TMY3.epw"
#export ENERGYPLUS_WEATHER="${WEATHER_DIR}/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw"
#export ENERGYPLUS_WEATHER="${WEATHER_DIR}/USA_VA_Sterling-Washington.Dulles.Intl.AP.724030_TMY3.epw"
#export ENERGYPLUS_WEATHER="${WEATHER_DIR}/USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw,${WEATHER_DIR}/USA_CO_Golden-NREL.724666_TMY3.epw,${WEATHER_DIR}/USA_FL_Tampa.Intl.AP.722110_TMY3.epw"

# Ouput directory "openai-YYYY-MM-DD-HH-MM-SS-mmmmmm" is created in
# the directory specified by ENERGYPLUS_LOGBASE or in the current directory if not specified.
export ENERGYPLUS_LOGBASE="${HOME}/eplog"

# Model file. Uncomment one.
#export ENERGYPLUS_MODEL="${MODEL_DIR}/2ZoneDataCenterHVAC_wEconomizer_Temp.idf"     # Temp. setpoint control
export ENERGYPLUS_MODEL="${MODEL_DIR}/2ZoneDataCenterHVAC_wEconomizer_Temp_Fan.idf" # Temp. setpoint and fan control

# Run command (example)
# $ time python3 -m baselines_energyplus.trpo_mpi.run_energyplus --num-timesteps 1000000000

# Monitoring (example)
# $ python3 -m baselines_energyplus.common.plot_energyplus




second
in rl-testbed-for-energyplus/baselines_energyplus/common/energyplus_util.py 
add import gym_energyplus

**Comment by Vesyrak** [comment]
Had the same issue when testing _run_energyplus.py_, environment is defined in _gym_energyplus/\_\_init\_\_.py_.
Issue can be resolved by adding the following to _run_energyplus.py_:
`import gym_energyplus`
