### ISSUE TITLE
What is Power made of?

### ISSUE THREAD

**Issue by yashviagrawal** [IBM/rl-testbed-for-energyplus#90]
@antoine-galataud @takaomoriyama 
Hello, how is the power being measured? 
In which file is the power data mentioned?
What does the building power and hvac power comprise of?

**Comment by prsi7** [comment]
@yashviagrawal hi I know this is irrelevant of this question but as you have more knowledge about this project, can you please guide me an small issue regarding plotting the Graph..  i have seen that you too initiated the same issue but later closed. I am at the same spot where i have Eplog file with outputs but can't plot graph.  i am using this command as mentioned.
$ python3 -m baselines_energyplus.common.plot_energyplus -l <openai file directory>
l Please let me know what I'm doing wrong or i need to plot the graph on different platform

**Comment by yashviagrawal** [comment]
@prsi7 
the command to plot the graph is:
python3 -m baselines_energyplus.common.plot_energyplus

**Comment by prsi7** [comment]
thank you for replying this command is executing with this output. 

energyplus_locate_log_dir: /root/eplog/openai-2022-05-11-08-54-27-400616
Logging to /tmp/openai-2022-05-12-07-38-39-657496
Monitor: filename=/tmp/openai-2022-05-12-07-38-39-657496
energyplus_plot.plot log=/root/eplog/openai-2022-05-11-08-54-27-400616
episode 2
read_episode: file=/root/eplog/openai-2022-05-11-08-54-27-400616/output/episode-00000002/eplusout.csv.gz
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Whole Building:Facility Total Building Electric Demand Power [W](Hourly)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/rl-testbed-for-energyplus/baselines_energyplus/common/plot_energyplus.py", line 42, in <module>
    main()
  File "/root/rl-testbed-for-energyplus/baselines_energyplus/common/plot_energyplus.py", line 39, in main
    energyplus_plot(args.env, log_dir=args.log_dir, csv_file=args.csv_file, dump_timesteps=args.dump_timesteps, dump_episodes=args.dump_episodes)
  File "/root/rl-testbed-for-energyplus/baselines_energyplus/common/plot_energyplus.py", line 34, in energyplus_plot
    env.env.plot(log_dir=log_dir, csv_file=csv_file)
  File "/root/rl-testbed-for-energyplus/gym_energyplus/envs/energyplus_env.py", line 246, in plot
    self.ep_model.plot(log_dir=log_dir, csv_file=csv_file)
  File "/root/rl-testbed-for-energyplus/gym_energyplus/envs/energyplus_model.py", line 132, in plot
    self.show_progress()
  File "/root/rl-testbed-for-energyplus/gym_energyplus/envs/energyplus_model.py", line 200, in show_progress
    self.update_episode(self.num_episodes - 1)
  File "/root/rl-testbed-for-energyplus/gym_energyplus/envs/energyplus_model.py", line 262, in update_episode
    self.plot_episode(ep)
  File "/root/rl-testbed-for-energyplus/gym_energyplus/envs/energyplus_model_2ZoneDataCenterHVAC_wEconomizer_Temp_Fan.py", line 357, in plot_episode
    self.read_episode(ep)
  File "/root/rl-testbed-for-energyplus/gym_energyplus/envs/energyplus_model_2ZoneDataCenterHVAC_wEconomizer_Temp_Fan.py", line 318, in read_episode
    self.total_building_electric_demand_power = df['Whole Building:Facility Total Building Electric Demand Power [W](Hourly)']
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Whole Building:Facility Total Building Electric Demand Power [W](Hourly)'energyplus_locate_log_dir: /root/eplog/openai-2022-05-11-08-54-27-400616
Logging to /tmp/openai-2022-05-12-07-38-39-657496
Monitor: filename=/tmp/openai-2022-05-12-07-38-39-657496
energyplus_plot.plot log=/root/eplog/openai-2022-05-11-08-54-27-400616
episode 2
read_episode: file=/root/eplog/openai-2022-05-11-08-54-27-400616/output/episode-00000002/eplusout.csv.gz
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Whole Building:Facility Total Building Electric Demand Power [W](Hourly)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/rl-testbed-for-energyplus/baselines_energyplus/common/plot_energyplus.py", line 42, in <module>
    main()
  File "/root/rl-testbed-for-energyplus/baselines_energyplus/common/plot_energyplus.py", line 39, in main
    energyplus_plot(args.env, log_dir=args.log_dir, csv_file=args.csv_file, dump_timesteps=args.dump_timesteps, dump_episodes=args.dump_episodes)
  File "/root/rl-testbed-for-energyplus/baselines_energyplus/common/plot_energyplus.py", line 34, in energyplus_plot
    env.env.plot(log_dir=log_dir, csv_file=csv_file)
  File "/root/rl-testbed-for-energyplus/gym_energyplus/envs/energyplus_env.py", line 246, in plot
    self.ep_model.plot(log_dir=log_dir, csv_file=csv_file)
  File "/root/rl-testbed-for-energyplus/gym_energyplus/envs/energyplus_model.py", line 132, in plot
    self.show_progress()
  File "/root/rl-testbed-for-energyplus/gym_energyplus/envs/energyplus_model.py", line 200, in show_progress
    self.update_episode(self.num_episodes - 1)
  File "/root/rl-testbed-for-energyplus/gym_energyplus/envs/energyplus_model.py", line 262, in update_episode
    self.plot_episode(ep)
  File "/root/rl-testbed-for-energyplus/gym_energyplus/envs/energyplus_model_2ZoneDataCenterHVAC_wEconomizer_Temp_Fan.py", line 357, in plot_episode
    self.read_episode(ep)
  File "/root/rl-testbed-for-energyplus/gym_energyplus/envs/energyplus_model_2ZoneDataCenterHVAC_wEconomizer_Temp_Fan.py", line 318, in read_episode
    self.total_building_electric_demand_power = df['Whole Building:Facility Total Building Electric Demand Power [W](Hourly)']
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Whole Building:Facility Total Building Electric Demand Power [W](Hourly)'

**Comment by antoine-galataud** [comment]
@yashviagrawal please have a look at [EnergyPlus documentation](https://bigladdersoftware.com/epx/docs/22-1/engineering-reference/whole-facility-electric-service.html)
